// Generated by CoffeeScript 1.12.2
(function() {
  "use strict";
  var expressUtil, util;

  util = require('./util');

  expressUtil = require('./expressUtil');

  module.exports.Util = function() {
    return util;
  };

  module.exports.ExpressUtil = function() {
    return expressUtil;
  };

}).call(this);
