// Generated by CoffeeScript 1.12.2
(function() {
  var dateUtil;

  dateUtil = require('../bin/dateUtil');

  describe("Test la librairie utilDate du module common\n", function() {

    /*====================================================================================
     *                         Tests des methodes 
    #===================================================================================
     */

    /*
     * Test de la méthode toBuild
     */
    return describe("Test de la méthode : toBuild\n", function() {
      it("Creer une date au format 'DD/MM/YYYY avec dateString = null, devrait retourner null", function() {
        return expect(dateUtil.toBuild(null, "DD/MM/YYYY")).toBeNull();
      });
      it("Creer une date au format 'DD/MM/YYYY avec dateString = undefined, devrait retourner null", function() {
        return expect(dateUtil.toBuild(void 0, "DD/MM/YYYY")).toBeNull();
      });
      it("Creer une date au format 'DD/MM/YYYY avec dateString = {}, devrait retourner null", function() {
        return expect(dateUtil.toBuild({}, "DD/MM/YYYY")).toBeNull();
      });
      it("Creer une date au format 'DD/MM/YYYY, devrait retourner une date valide correspondant à 24/10/1993", function() {
        return expect(dateUtil.toBuild("24/10/1993", "DD/MM/YYYY")).toEqual(new Date("10/24/1993"));
      });
      it("Creer une date au format 'DD/MM/YY, devrait retourner une date valide correspondant à 24/10/1993", function() {
        return expect(dateUtil.toBuild("24/10/93", "DD/MM/YY")).toEqual(new Date("10/24/1993"));
      });
      it("Creer une date au format 'DD-MM-YYYY, devrait retourner une date valide correspondant à 24/10/1993", function() {
        return expect(dateUtil.toBuild("24-10-1993", "DD-MM-YYYY")).toEqual(new Date("10/24/1993"));
      });
      it("Creer une date au format 'DD-MM-YY, devrait retourner une date valide correspondant à 24/10/1993", function() {
        return expect(dateUtil.toBuild("24-10-93", "DD-MM-YY")).toEqual(new Date("10/24/1993"));
      });
      it("Creer une date au format 'MM/DD/YYYY, devrait retourner une date valide correspondant à 24/10/1993", function() {
        return expect(dateUtil.toBuild("10/24/1993", "MM/DD/YYYY")).toEqual(new Date("10/24/1993"));
      });
      it("Creer une date au format 'MM/DD/YY, devrait retourner une date valide correspondant à 24/10/1993", function() {
        return expect(dateUtil.toBuild("10/24/93", "MM/DD/YY")).toEqual(new Date("10/24/1993"));
      });
      it("Creer une date au format 'MM-DD-YYYY, devrait retourner une date valide correspondant à 24/10/1993", function() {
        return expect(dateUtil.toBuild("10-24-1993", "MM-DD-YYYY")).toEqual(new Date("10/24/1993"));
      });
      it("Creer une date au format 'MM-DD-YY, devrait retourner une date valide correspondant à 24/10/1993", function() {
        return expect(dateUtil.toBuild("10-24-93", "MM-DD-YY")).toEqual(new Date("10/24/1993"));
      });
      it("Creer une date au format 'MM-DD-YY, devrait retourner une date invalide", function() {
        return expect((dateUtil.toBuild("blabla", "MM-DD-YY")).getTime()).toBeNaN();
      });
      it("Creer une date sans format, devrait retourner une date valide correspondant à 24/10/1993", function() {
        return expect(dateUtil.toBuild("10/24/1993")).toEqual(new Date("10/24/1993"));
      });
      it("Creer une date sans format avec dateString = 24/10/1993, devrait retourner une date invalide", function() {
        return expect((dateUtil.toBuild("24/10/1993")).getTime()).toBeNaN();
      });
      it("Change le format par défaut, devrait retourner une date valide correspondant à 24/10/1993", function() {
        dateUtil.setDefaultFormat("DD/MM/YYYY");
        expect(dateUtil.toBuild("24/10/1993")).toEqual(new Date("10/24/1993"));
        return dateUtil.setDefaultFormat("MM/DD/YYYY");
      });
      it("Creer une date avec format bidon, devrait retourner une date valide correspondant à 24/10/1993", function() {
        return expect(dateUtil.toBuild("10/24/1993", {})).toEqual(new Date("10/24/1993"));
      });
      return it("Creer une date avec format 'bidon', devrait retourner une date valide correspondant à 24/10/1993", function() {
        return expect(dateUtil.toBuild("10/24/1993", "bidon")).toEqual(new Date("10/24/1993"));
      });
    });
  });


  /*
  var dateUtil = require('./bin/dateUtil');
  dateUtil.toBuild('24/10/1993', 'DD/MM/YYYY');
   */

}).call(this);
